// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aryprvxhwmlqfxfdajsi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFyeXBydnhod21scWZ4ZmRhanNpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5NTExMjUsImV4cCI6MjA1OTUyNzEyNX0.Ewz5Ypb-XgC7QlYZ7-hlDbSyKfefVr4rJTZMaQTjnro";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);